export const products = [
  {
    id_produto: 13,
    nome: "Naruto",
    categoria: "mangás",
    editora: "Panini",
    preço: 30.9,
    volume: "01",
    tipo: "",
    coleção: "",
    estilo: "",
    jogadores: "",
    linha: "",
    imagem:
      "https://d14d9vp3wdof84.cloudfront.net/image/589816272436/image_0i17sgukfl5mrci6cq5t4gh574/-S300-FWEBP",
  },
  {
    id_produto: 17,
    nome: "Superman Especial",
    categoria: "quadrinhos",
    editora: "Panini",
    preço: 45,
    volume: "",
    tipo: null,
    coleção: null,
    estilo: null,
    jogadores: null,
    linha: null,
    imagem:
      "https://d14d9vp3wdof84.cloudfront.net/image/589816272436/image_8f124vanol55fdi0v6fp89ie53/-S897-FWEBP",
  },
  {
    id_produto: 14,
    nome: "Batman",
    categoria: "quadrinhos",
    editora: "Panini",
    preço: 20,
    volume: "107",
    tipo: "",
    coleção: "",
    estilo: "",
    jogadores: "",
    linha: "",
    imagem:
      "https://d14d9vp3wdof84.cloudfront.net/image/589816272436/image_vc36q9othp2dr71nmh7kj4me07/-S300-FWEBP",
  },
  {
    id_produto: 15,
    nome: "Dixit",
    categoria: "boardgames",
    editora: "Galápagos Jogos",
    preço: 302.9,
    volume: "",
    tipo: "Jogo base",
    coleção: "",
    estilo: "Todos contra todos",
    jogadores: "3 a 8 jogadores",
    linha: "",
    imagem:
      "https://ecclesiae.com.br/image/cache/data/api/produtos/12517-515x800.jpg?1670959481",
  },
  {
    id_produto: 16,
    nome: "Hunter x Hunter",
    categoria: "mangás",
    editora: "JBC",
    preço: 19.9,
    volume: "02",
    tipo: "",
    coleção: "",
    estilo: "",
    jogadores: "",
    linha: "",
    imagem:
      "https://www.jbchost.com.br/editorajbc/wp-content/uploads/2020/12/manga-hunter-x-hunter-02-capa.jpg",
  },
  {
    id_produto: 18,
    nome: "Wolverine",
    categoria: "quadrinhos",
    editora: "Panini",
    preço: 34.9,
    volume: "19",
    tipo: null,
    coleção: null,
    estilo: null,
    jogadores: null,
    linha: null,
    imagem:
      "https://d14d9vp3wdof84.cloudfront.net/image/589816272436/image_d7jqto5q2l043b7b1c1p88974l/-S897-FWEBP",
  },
  {
    id_produto: 19,
    nome: "Vingadores",
    categoria: "quadrinhos",
    editora: "Panini",
    preço: 27.9,
    volume: "07/64",
    tipo: null,
    coleção: null,
    estilo: null,
    jogadores: null,
    linha: null,
    imagem:
      "https://d14d9vp3wdof84.cloudfront.net/image/589816272436/image_d534a2dm0h1sb92qh0h11lkb5e/-S897-FWEBP",
  },
  {
    id_produto: 20,
    nome: "Demolidor Por Mark Waid",
    categoria: "quadrinhos",
    editora: "Panini",
    preço: 74.9,
    volume: "05",
    tipo: null,
    coleção: null,
    estilo: null,
    jogadores: null,
    linha: null,
    imagem:
      "https://d14d9vp3wdof84.cloudfront.net/image/589816272436/image_7fr8ntujn52ff3e3dov51iv73h/-S897-FWEBP",
  },
  {
    id_produto: 21,
    nome: "A Queda de X Especial",
    categoria: "quadrinhos",
    editora: "Panini",
    preço: 69.9,
    volume: "01",
    tipo: null,
    coleção: null,
    estilo: null,
    jogadores: null,
    linha: null,
    imagem:
      "https://d14d9vp3wdof84.cloudfront.net/image/589816272436/image_4h1915ukdp65h81c8r7phut521/-S897-FWEBP",
  },
  {
    id_produto: 22,
    nome: "Saga do Homem-Aranha",
    categoria: "quadrinhos",
    editora: "Panini",
    preço: 39.9,
    volume: "12",
    tipo: null,
    coleção: null,
    estilo: null,
    jogadores: null,
    linha: null,
    imagem:
      "https://d14d9vp3wdof84.cloudfront.net/image/589816272436/image_2c1ia8lchd6lr2q2949boc6a6i/-S897-FWEBP",
  },
  {
    id_produto: 23,
    nome: "Soul Eater Perfect Edition",
    categoria: "mangás",
    editora: "JBC",
    preço: 79.9,
    volume: "08",
    tipo: null,
    coleção: null,
    estilo: null,
    jogadores: null,
    linha: null,
    imagem:
      "https://www.jbchost.com.br/editorajbc/wp-content/uploads/2024/03/soul-eater-perfect-edition-08-sobrecapa-400x560.jpg",
  },
  {
    id_produto: 25,
    nome: "Fullmetal Alchemist - Edição Especial de Aniversário de 20 Anos",
    categoria: "mangás",
    editora: "JBC",
    preço: 76.9,
    volume: "",
    tipo: null,
    coleção: null,
    estilo: null,
    jogadores: null,
    linha: null,
    imagem:
      "https://www.jbchost.com.br/editorajbc/wp-content/uploads/2024/03/fma-20anos-capa-400x560.jpg",
  },
  {
    id_produto: 26,
    nome: "Jujutsu Kaisen: Batalha de Feiticeiros",
    categoria: "mangás",
    editora: "Panini",
    preço: 36.9,
    volume: "0",
    tipo: null,
    coleção: null,
    estilo: null,
    jogadores: null,
    linha: null,
    imagem:
      "https://d14d9vp3wdof84.cloudfront.net/image/589816272436/image_fuj27at48h7c700gjdm76m3a6k/-S897-FWEBP",
  },
  {
    id_produto: 27,
    nome: "One Piece Receitas Piratas",
    categoria: "mangás",
    editora: "Panini",
    preço: 99.9,
    volume: "01",
    tipo: null,
    coleção: null,
    estilo: null,
    jogadores: null,
    linha: null,
    imagem:
      "https://d14d9vp3wdof84.cloudfront.net/image/589816272436/image_7atqjrtord26f20lqtub6rqd3e/-S897-FWEBP",
  },
  {
    id_produto: 24,
    nome: "Yona",
    categoria: "mangás",
    editora: "JBC",
    preço: 57.9,
    volume: "04",
    tipo: null,
    coleção: null,
    estilo: null,
    jogadores: null,
    linha: null,
    imagem:
      "https://www.jbchost.com.br/editorajbc/wp-content/uploads/2024/03/capaamazon-yona4-400x606.jpg",
  },
  {
    id_produto: 28,
    nome: "7 Wonders Duel",
    categoria: "boardgames",
    editora: "Galápagos Jogos",
    preço: 249.99,
    volume: null,
    tipo: "Jogo base",
    coleção: null,
    estilo: "Um contra o outro",
    jogadores: "2",
    linha: null,
    imagem:
      "https://www.mundogalapagos.com.br/ccstore/v1/images/?source=/file/v7842341387415093920/products/7WO101_3D.jpg",
  },
  {
    id_produto: 29,
    nome: "Histórias Sinistras",
    categoria: "boardgames",
    editora: "Galápagos Jogos",
    preço: 39.99,
    volume: null,
    tipo: "Jogo base",
    coleção: null,
    estilo: "Cooperativo - Adivinhação",
    jogadores: "1 a 99",
    linha: null,
    imagem:
      "https://www.mundogalapagos.com.br/ccstore/v1/images/?source=/file/v504465764444186594/products/BLK001_3D.jpg",
  },
  {
    id_produto: 30,
    nome: "Pandemic",
    categoria: "boardgames",
    editora: "Galápagos Jogos",
    preço: 299.99,
    volume: null,
    tipo: "Jogo Base",
    coleção: null,
    estilo: "Cooperativo",
    jogadores: "2 a 4",
    linha: null,
    imagem:
      "https://www.mundogalapagos.com.br/ccstore/v1/images/?source=/file/v6889823979222251628/products/PAN001_3D.jpg",
  },
  {
    id_produto: 31,
    nome: "Bitoku - Resutoran Expansão",
    categoria: "boardgames",
    editora: "Devir",
    preço: 190,
    volume: null,
    tipo: "Expansão",
    coleção: null,
    estilo: "Todos contra todos",
    jogadores: "1 a 4",
    linha: null,
    imagem:
      "https://devir.com.br/wp-content/uploads/2024/03/IMG_5592-780x585.jpg",
  },
  {
    id_produto: 32,
    nome: "Deck Estrutural Reis de Fogo",
    categoria: "cardgames",
    editora: "Devir",
    preço: 59.9,
    volume: null,
    tipo: "Deck",
    coleção: "Reis de Fogo",
    estilo: null,
    jogadores: null,
    linha: "Yu-Gi-Oh! TCG",
    imagem:
      "https://www.yugioh-card.com/lat-am/pt/wp-content/uploads/2023/09/SR14_550.png",
  },
  {
    id_produto: 33,
    nome: "Batalha das Lendas: Vingança do Terminal",
    categoria: "cardgames",
    editora: "Devir",
    preço: 24.9,
    volume: null,
    tipo: "Booster",
    coleção: "Batalha das Lendas: Vingança do Terminal",
    estilo: null,
    jogadores: null,
    linha: "Yu-Gi-Oh! TCG",
    imagem:
      "https://www.yugioh-card.com/lat-am/pt/wp-content/uploads/2024/02/BLTR_Foil_550x550.png",
  },
  {
    id_produto: 34,
    nome: "MTG - Ikoria Terra de Colossos Booster",
    categoria: "cardgames",
    editora: "Wizards of The Coast",
    preço: 25,
    volume: null,
    tipo: "Booster",
    coleção: "Ikoria Terra de Colossos",
    estilo: null,
    jogadores: null,
    linha: "Magic The Gathering",
    imagem: "https://m.media-amazon.com/images/I/71Yz2HwKv1L._AC_SL1500_.jpg",
  },
  {
    id_produto: 35,
    nome: "MTG - Commander Collection: Black",
    categoria: "cardgames",
    editora: "Wizards of the Coast",
    preço: 300,
    volume: null,
    tipo: "Commander Deck",
    coleção: "Commander Collection",
    estilo: null,
    jogadores: null,
    linha: "Magic The Gathering",
    imagem:
      "https://images.tcdn.com.br/img/img_prod/1257377/magic_commander_collection_black_485_1_f2e6615be54488ef6965a918706957cf.jpg",
  },
  {
    id_produto: 36,
    nome: "Dungeons & Dragons - Livro do jogador",
    categoria: "rpgs",
    editora: "Galápagos Jogos",
    preço: 279.9,
    volume: null,
    tipo: "Livro Básico",
    coleção: null,
    estilo: null,
    jogadores: null,
    linha: "Dungeons & Dragons 5a Edição",
    imagem: "https://m.media-amazon.com/images/I/71kM9wdaeHL._AC_SL1051_.jpg",
  },
];
